version: '3.9'
services:
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: some_password
      PGUSER: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
  backend:
    build:
      context: ./back
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=some_password
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=5432
      - SENDER_EMAIL=noreply@tasera.fi
      - SERVER_HOST=http://localhost:8000
    ports:
      - 8000:8000
      - 5858:5858 # node debugger
    volumes:
      - '/app/node_modules/'
      - ./back:/app
    command: >
      /bin/sh -c "npx knex migrate:latest
      && npx knex seed:run
      && nodemon --inspect=0.0.0.0:5858 --legacy-watch server.js"
  frontend:
    build:
      context: ./front
    restart: always
    depends_on:
      - backend
    ports:
      - 5173:5173
    environment:
      - VITE_PROXY_API=http://backend:8000
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    links:
      - backend

