name: E2E Tests with Docker Compose

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.dev.yaml up -d --build

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./test
          start: echo "App already started via Docker Compose"
          wait-on: http://localhost:5173
          wait-on-timeout: 120

