name: End-to-end Tests

env: 
  DB: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: 127.0.0.1
  SENDER_EMAIL: noreply@tasera.fi
  SERVER_HOST: http://127.0.0.1:3000
  PROXY_HOSTNAME: 127.0.0.1
  PROXY_PORT: 8000
  DB_PORT: 5432

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12
        env:
          DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install app dependencies
        run: npm install && cd ../front && yarn
        working-directory: ./back

      - name: Run DB Migrations
        run: npx knex migrate:latest && npx knex seed:run
        working-directory: ./back

      - name: Install Cypress dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          working-directory: back

      - name: run backend
        run: |
          npm run start &
          sleep 20s
        working-directory: ./back

      - name: run frontend
        run: |
          yarn run start &
          npx wait-on http://127.0.0.1:3000
        working-directory: ./front


      - name: Run Integration Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: back
