name: Integration Tests

on:
  push:
    branches: [e2e-testing]
  pull_request:
    branches: [master]

jobs:
  postgres-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - run: npm ci
      working-directory: ./postgres
    - run: node client.js
      working-directory: ./postgres
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ postgres-job.services.postgres.ports[5432] }}

  build-and-test:
    needs: postgres-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd back && npm install && cd ../front && npm install && cd ..

      - name: Run Migrations
        run: |
          sh env DB_USER=postgres \
          DB_PASSWORD=postgres \
          DB=postgres \
          bash -c 'cd back && npx knex migrate:latest && npx knex seed:run && cd ..'

      - name: Run App
        run: |
          sh env DB_USER=postgres \
          DB_PASSWORD=postgres \
          DB=postgres \
          SENDER_EMAIL=noreply@tasera.fi \
          bash -c 'cd back && npm run dev:withFront'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start