name: Integration Tests

on:
  push:
    branches: [e2e-testing]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Application
        run: docker-compose -f docker-compose.dev.yaml up

  test:
    runs-on: ubuntu-latest
    depends_on:
      build:
        condition: service_healthy
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start