name: Integration Tests

on:
  push:
    branches: [e2e-testing]
  pull_request:
    branches: [master]

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Application
        run: docker-compose -f docker-compose.dev.yaml up
  build:
    test:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start