name: Integration Tests

on:
  push:
    branches: [e2e-testing]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install app dependencies
        run: npm install && cd ../front && npm install
        working-directory: ./back

      - name: Remove cached cypress files
        run: cypress cache prune
        working-directory: ./back

      - name: Install Cypress dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          working-directory: back

      - name: Run postgres DB
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: postgres

      - name: Run frontend
        run: npm start &
        working-directory: ./back

      - name: Run Integration Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: node ./server.js &
          env: DB_USER=postgres, DB_PASSWORD=postgres, DB_HOST=postgres, SENDER_EMAIL=noreply@tasera.fi
          # wait-on: 'npx wait-on --timeout 5000 http://localhost:8000'
          browser: chrome
          headless: true
          working-directory: back

# jobs:
#   setup:
#     runs-on: ubuntu-latest
    # container:
    #   image: node:10.18-jessie

  #   steps:


  # e2e-tests:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install app dependencies
  #       run: npm install && cd ../front && npm install
  #       working-directory: ./back

      # - name: Install Cypress dependencies
      #   run: sudo apt-get install -y libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      # - name: Run Migrations
      #   run: npx knex migrate:latest && npx knex seed:run
      #   working-directory: ./back
      #   env:
      #     DB_USER: postgres
      #     DB_PASSWORD: postgres
      #     DB_HOST: postgres
      #     POSTGRES_HOST: postgres
      #     POSTGRES_PORT: 5432
      #     # POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

  # integration-tests:
  #   image: cypress-io/github-action@v2
  #   needs: setup
  #   script:
  #     - node ./server.js &
      # - npx cypress run --browser firefox
      # env: DB_USER=postgres, DB_PASSWORD=postgres, DB_HOST=postgres, SENDER_EMAIL=noreply@tasera.fi
      # working-directory: back
