name: Integration Tests

on:
  push:
    branches: [e2e-testing]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install app dependencies
        run: npm install && cd ../front && npm install
        working-directory: ./back

      - name: Install Cypress dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          working-directory: back

      - name: Run postgres DB
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: postgres

      # running cypress starts the backend automatically
      - name: Run Integration Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm start &
          env: DB_USER=postgres, DB_PASSWORD=postgres, DB_HOST=postgres, SENDER_EMAIL=noreply@tasera.fi
          browser: chrome
          headless: true
          working-directory: back
