name: Integration Tests

on:
  push:
    branches: [e2e-testing]
  pull_request:
    branches: [master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: node:10.18-jessie

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install && cd ../front && npm install && cd ..
      working-directory: ./back

    - name: Run Migrations
      run: npx knex migrate:latest && npx knex seed:run
      working-directory: ./back
      env:
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: postgres
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

    # - name: Run Backend
    #   run: node server.js &
    #   working-directory: ./back
    #   env:
    #     DB_USER: postgres
    #     DB_PASSWORD: postgres
    #     DB_HOST: postgres
    #     SENDER_EMAIL: noreply@tasera.fi

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v2
      with:
        start: node ./back/server.js &
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: postgres
          SENDER_EMAIL: noreply@tasera.fi


